"""cria_tabelas_orcamentos_e_vendas

Revision ID: 0c5735d2929f
Revises: 876359399b80
Create Date: 2026-06-22 23:33:56.536489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c5735d2929f'
down_revision: Union[str, Sequence[str], None] = '876359399b80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orcamentos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('aberto', 'aprovado', 'recusado', name='statusorcamentoenum'), nullable=False),
    sa.Column('validade_dias', sa.Integer(), nullable=False),
    sa.Column('data_criacao', sa.Date(), nullable=False),
    sa.Column('data_validade', sa.Date(), nullable=False),
    sa.Column('desconto_percentual', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('observacoes', sa.String(length=500), nullable=True),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], name=op.f('fk_orcamentos_cliente_id_clientes')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_orcamentos')),
    sa.UniqueConstraint('numero', name=op.f('uq_orcamentos_numero'))
    )
    op.create_table('itens_orcamento',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('orcamento_id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('preco_unitario', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.CheckConstraint('quantidade > 0', name=op.f('ck_itens_orcamento_quantidade_positiva')),
    sa.ForeignKeyConstraint(['orcamento_id'], ['orcamentos.id'], name=op.f('fk_itens_orcamento_orcamento_id_orcamentos')),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], name=op.f('fk_itens_orcamento_produto_id_produtos')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_itens_orcamento'))
    )
    op.create_table('vendas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('orcamento_id', sa.Integer(), nullable=True),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('aberta', 'finalizada', 'cancelada', name='statusvendaenum'), nullable=False),
    sa.Column('desconto_percentual', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], name=op.f('fk_vendas_cliente_id_clientes')),
    sa.ForeignKeyConstraint(['orcamento_id'], ['orcamentos.id'], name=op.f('fk_vendas_orcamento_id_orcamentos')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vendas'))
    )
    op.create_table('itens_venda',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('venda_id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('preco_unitario', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.CheckConstraint('quantidade > 0', name=op.f('ck_itens_venda_quantidade_positiva')),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], name=op.f('fk_itens_venda_produto_id_produtos')),
    sa.ForeignKeyConstraint(['venda_id'], ['vendas.id'], name=op.f('fk_itens_venda_venda_id_vendas')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_itens_venda'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('itens_venda')
    op.drop_table('vendas')
    op.drop_table('itens_orcamento')
    op.drop_table('orcamentos')
    # ### end Alembic commands ###
