"""cria tabelas categorias e produtos

Revision ID: 150ecb145dad
Revises: 594eca582c95
Create Date: 2026-06-21 14:47:05.946658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '150ecb145dad'
down_revision: Union[str, Sequence[str], None] = '594eca582c95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_categorias')),
    sa.UniqueConstraint('nome', name=op.f('uq_categorias_nome'))
    )
    op.create_table('produtos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('descricao', sa.String(length=500), nullable=True),
    sa.Column('tipo', sa.Enum('produto', 'servico', name='tipoenum'), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.Column('controla_estoque', sa.Boolean(), nullable=False),
    sa.Column('estoque_atual', sa.Integer(), nullable=False),
    sa.Column('estoque_minimo', sa.Integer(), nullable=False),
    sa.Column('preco_custo', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('preco_venda', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('permite_desconto', sa.Boolean(), nullable=False),
    sa.Column('desconto_maximo_percentual', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('produto_em_promocao', sa.Boolean(), nullable=False),
    sa.Column('preco_promocional', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('promocao_inicio', sa.Date(), nullable=True),
    sa.Column('promocao_fim', sa.Date(), nullable=True),
    sa.Column('codigo_barras', sa.String(length=50), nullable=True),
    sa.Column('unidade_medida', sa.String(length=10), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('desconto_maximo_percentual >= 0 AND desconto_maximo_percentual <= 100', name=op.f('ck_produtos_desconto_maximo_valido')),
    sa.CheckConstraint('estoque_atual >= 0', name=op.f('ck_produtos_estoque_nao_negativo')),
    sa.CheckConstraint('preco_promocional IS NULL OR preco_promocional <= preco_venda', name=op.f('ck_produtos_preco_promocional_valido')),
    sa.CheckConstraint('preco_venda >= 0', name=op.f('ck_produtos_preco_venda_nao_negativo')),
    sa.CheckConstraint('promocao_inicio IS NULL OR promocao_fim IS NULL OR promocao_fim >= promocao_inicio', name=op.f('ck_produtos_datas_promocao_validas')),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], name=op.f('fk_produtos_categoria_id_categorias')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_produtos'))
    )
    op.create_index(op.f('ix_produtos_codigo_barras'), 'produtos', ['codigo_barras'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_produtos_codigo_barras'), table_name='produtos')
    op.drop_table('produtos')
    op.drop_table('categorias')
    # ### end Alembic commands ###
