"""cria tabelas entrada mercadorias e adiciona campos custo a produtos

Revision ID: 9a4823b3ecbf
Revises: 5fd03d193769
Create Date: 2026-06-22 18:06:42.727906

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a4823b3ecbf'
down_revision: Union[str, Sequence[str], None] = '5fd03d193769'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entradas_mercadorias',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fornecedor_id', sa.Integer(), nullable=False),
    sa.Column('numero_nota', sa.String(length=50), nullable=True),
    sa.Column('data_entrada', sa.Date(), nullable=False),
    sa.Column('observacoes', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('rascunho', 'confirmada', name='statusentradaenum'), nullable=False),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['fornecedor_id'], ['fornecedores.id'], name=op.f('fk_entradas_mercadorias_fornecedor_id_fornecedores')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_entradas_mercadorias'))
    )
    op.create_table('itens_entrada',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entrada_id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('custo_unitario', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.CheckConstraint('custo_unitario >= 0', name=op.f('ck_itens_entrada_custo_unitario_nao_negativo')),
    sa.CheckConstraint('quantidade > 0', name=op.f('ck_itens_entrada_quantidade_positiva')),
    sa.ForeignKeyConstraint(['entrada_id'], ['entradas_mercadorias.id'], name=op.f('fk_itens_entrada_entrada_id_entradas_mercadorias')),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], name=op.f('fk_itens_entrada_produto_id_produtos')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_itens_entrada'))
    )
    op.add_column('produtos', sa.Column('preco_custo_anterior', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('produtos', sa.Column('custo_medio', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('produtos', 'custo_medio')
    op.drop_column('produtos', 'preco_custo_anterior')
    op.drop_table('itens_entrada')
    op.drop_table('entradas_mercadorias')
    # ### end Alembic commands ###
