"""cria_modulo_pdv_pagamentos_e_devolucoes

Revision ID: ab7ff4570cf0
Revises: f4e5121a3a16
Create Date: 2026-06-23 07:58:21.418185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab7ff4570cf0'
down_revision: Union[str, Sequence[str], None] = 'f4e5121a3a16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devolucoes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('venda_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('troca', 'reembolso', name='tipodevolucaoenum'), nullable=False),
    sa.Column('motivo', sa.String(length=500), nullable=False),
    sa.Column('valor_reembolso', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('forma_reembolso', sa.String(length=20), nullable=True),
    sa.Column('status', sa.Enum('pendente', 'concluida', name='statusdevolucaoenum'), nullable=False),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['venda_id'], ['vendas.id'], name=op.f('fk_devolucoes_venda_id_vendas')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_devolucoes'))
    )
    op.create_table('pagamentos_venda',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('venda_id', sa.Integer(), nullable=False),
    sa.Column('forma', sa.String(length=20), nullable=False),
    sa.Column('valor', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('valor > 0', name=op.f('ck_pagamentos_venda_valor_positivo')),
    sa.ForeignKeyConstraint(['venda_id'], ['vendas.id'], name=op.f('fk_pagamentos_venda_venda_id_vendas')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pagamentos_venda'))
    )
    op.create_table('itens_devolucao',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('devolucao_id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('produto_substituto_id', sa.Integer(), nullable=True),
    sa.CheckConstraint('quantidade > 0', name=op.f('ck_itens_devolucao_quantidade_positiva')),
    sa.ForeignKeyConstraint(['devolucao_id'], ['devolucoes.id'], name=op.f('fk_itens_devolucao_devolucao_id_devolucoes')),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], name=op.f('fk_itens_devolucao_produto_id_produtos')),
    sa.ForeignKeyConstraint(['produto_substituto_id'], ['produtos.id'], name=op.f('fk_itens_devolucao_produto_substituto_id_produtos')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_itens_devolucao'))
    )
    op.add_column('vendas', sa.Column('caixa_id', sa.Integer(), nullable=True))
    op.add_column('vendas', sa.Column('forma_pagamento_principal', sa.String(length=20), nullable=True))
    op.create_foreign_key(op.f('fk_vendas_caixa_id_caixas'), 'vendas', 'caixas', ['caixa_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_vendas_caixa_id_caixas'), 'vendas', type_='foreignkey')
    op.drop_column('vendas', 'forma_pagamento_principal')
    op.drop_column('vendas', 'caixa_id')
    op.drop_table('itens_devolucao')
    op.drop_table('pagamentos_venda')
    op.drop_table('devolucoes')
    # ### end Alembic commands ###
