"""cria_modulo_financeiro

Revision ID: f4e5121a3a16
Revises: 0c5735d2929f
Create Date: 2026-06-23 02:27:45.009782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4e5121a3a16'
down_revision: Union[str, Sequence[str], None] = '0c5735d2929f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('caixas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('hostname', sa.String(length=100), nullable=False),
    sa.Column('saldo_inicial', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_dinheiro', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_pix', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_debito', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_credito', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.Enum('aberto', 'fechado', name='statuscaixaenum'), nullable=False),
    sa.Column('aberto_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('fechado_em', sa.DateTime(), nullable=True),
    sa.Column('observacoes', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_caixas'))
    )
    op.create_table('contas_pagar',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('descricao', sa.String(length=200), nullable=False),
    sa.Column('valor_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('valor_pago', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.Enum('pendente', 'pago_parcialmente', 'pago', name='statuscontaenum'), nullable=False),
    sa.Column('vencimento', sa.Date(), nullable=False),
    sa.Column('fornecedor_id', sa.Integer(), nullable=True),
    sa.Column('parcela_numero', sa.Integer(), nullable=True),
    sa.Column('parcela_total', sa.Integer(), nullable=True),
    sa.Column('grupo_parcelas', sa.String(length=36), nullable=True),
    sa.Column('observacoes', sa.String(length=500), nullable=True),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('valor_total > 0', name=op.f('ck_contas_pagar_valor_total_positivo')),
    sa.ForeignKeyConstraint(['fornecedor_id'], ['fornecedores.id'], name=op.f('fk_contas_pagar_fornecedor_id_fornecedores')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contas_pagar'))
    )
    op.create_table('contas_receber',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('descricao', sa.String(length=200), nullable=False),
    sa.Column('valor_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('valor_pago', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.Enum('pendente', 'pago_parcialmente', 'pago', name='statuscontaenum'), nullable=False),
    sa.Column('vencimento', sa.Date(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('orcamento_id', sa.Integer(), nullable=True),
    sa.Column('parcela_numero', sa.Integer(), nullable=True),
    sa.Column('parcela_total', sa.Integer(), nullable=True),
    sa.Column('grupo_parcelas', sa.String(length=36), nullable=True),
    sa.Column('observacoes', sa.String(length=500), nullable=True),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('valor_total > 0', name=op.f('ck_contas_receber_valor_total_positivo')),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], name=op.f('fk_contas_receber_cliente_id_clientes')),
    sa.ForeignKeyConstraint(['orcamento_id'], ['orcamentos.id'], name=op.f('fk_contas_receber_orcamento_id_orcamentos')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contas_receber'))
    )
    op.create_table('pagamentos_conta_pagar',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('conta_pagar_id', sa.Integer(), nullable=False),
    sa.Column('valor', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('forma_pagamento', sa.Enum('dinheiro', 'pix', 'debito', 'credito', name='formapagamentoenum'), nullable=False),
    sa.Column('data_pagamento', sa.Date(), nullable=False),
    sa.Column('observacoes', sa.String(length=200), nullable=True),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('valor > 0', name=op.f('ck_pagamentos_conta_pagar_valor_positivo')),
    sa.ForeignKeyConstraint(['conta_pagar_id'], ['contas_pagar.id'], name=op.f('fk_pagamentos_conta_pagar_conta_pagar_id_contas_pagar')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pagamentos_conta_pagar'))
    )
    op.create_table('pagamentos_conta_receber',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('conta_receber_id', sa.Integer(), nullable=False),
    sa.Column('valor', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('forma_pagamento', sa.Enum('dinheiro', 'pix', 'debito', 'credito', name='formapagamentoenum'), nullable=False),
    sa.Column('data_pagamento', sa.Date(), nullable=False),
    sa.Column('observacoes', sa.String(length=200), nullable=True),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('valor > 0', name=op.f('ck_pagamentos_conta_receber_valor_positivo')),
    sa.ForeignKeyConstraint(['conta_receber_id'], ['contas_receber.id'], name=op.f('fk_pagamentos_conta_receber_conta_receber_id_contas_receber')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pagamentos_conta_receber'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pagamentos_conta_receber')
    op.drop_table('pagamentos_conta_pagar')
    op.drop_table('contas_receber')
    op.drop_table('contas_pagar')
    op.drop_table('caixas')
    # ### end Alembic commands ###
